export const SET_FILTER = 'SET_FILTER';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_COMPANY = 'SET_COMPANY';

//LOGIN AND USER
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_ID = 'SET_USER_ID';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';


export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_TASKS_ORDER_BY = 'SET_TASKS_ORDER_BY';
export const SET_TASKS_ASCENDING = 'SET_TASKS_ASCENDING';

export const SET_EXPENDITURES_ORDER_BY = 'SET_EXPENDITURES_ORDER_BY';
export const SET_EXPENDITURES_ASCENDING = 'SET_EXPENDITURES_ASCENDING';
