export const SET_FILTER = 'SET_FILTER';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_COMPANY = 'SET_COMPANY';

//LOGIN AND USER
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_ID = 'SET_USER_ID';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';

export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_TASKS_ORDER_BY = 'SET_TASKS_ORDER_BY';
export const SET_TASKS_ASCENDING = 'SET_TASKS_ASCENDING';

export const SET_EXPENDITURES_ORDER_BY = 'SET_EXPENDITURES_ORDER_BY';
export const SET_EXPENDITURES_ASCENDING = 'SET_EXPENDITURES_ASCENDING';

export const SET_PASSWORDS_ORDER_BY = 'SET_PASSWORDS_ORDER_BY';
export const SET_PASSWORDS_ASCENDING = 'SET_PASSWORDS_ASCENDING';

export const SET_CMDB_ORDER_BY = 'SET_CMDB_ORDER_BY';
export const SET_CMDB_ASCENDING = 'SET_CMDB_ASCENDING';

export const SET_WIKI_ORDER_BY = 'SET_WIKI_ORDER_BY';
export const SET_WIKI_ASCENDING = 'SET_WIKI_ASCENDING';

//STORAGE

export const STORAGE_SET_COMPANIES = 'STORAGE_SET_COMPANIES';
export const STORAGE_COMPANIES_ACTIVE = 'STORAGE_COMPANIES_ACTIVE';

export const STORAGE_SET_HELP_FILTERS = 'STORAGE_SET_HELP_FILTERS';
export const STORAGE_HELP_FILTERS_ACTIVE = 'STORAGE_HELP_FILTERS_ACTIVE';

export const STORAGE_SET_HELP_PRICELISTS = 'STORAGE_SET_HELP_PRICELISTS';
export const STORAGE_HELP_PRICELISTS_ACTIVE = 'STORAGE_HELP_PRICELISTS_ACTIVE';

export const STORAGE_SET_HELP_PRICES = 'STORAGE_SET_HELP_PRICES';
export const STORAGE_HELP_PRICES_ACTIVE = 'STORAGE_HELP_PRICES_ACTIVE';

export const STORAGE_SET_HELP_PROJECTS = 'STORAGE_SET_HELP_PROJECTS';
export const STORAGE_HELP_PROJECTS_ACTIVE = 'STORAGE_HELP_PROJECTS_ACTIVE';

export const STORAGE_SET_HELP_STATUSES = 'STORAGE_SET_HELP_STATUSES';
export const STORAGE_HELP_STATUSES_ACTIVE = 'STORAGE_HELP_STATUSES_ACTIVE';

export const STORAGE_SET_HELP_TAGS = 'STORAGE_SET_HELP_TAGS';
export const STORAGE_HELP_TAGS_ACTIVE = 'STORAGE_HELP_TAGS_ACTIVE';

export const STORAGE_SET_HELP_TASK_TYPES = 'STORAGE_SET_HELP_TASK_TYPES';
export const STORAGE_HELP_TASK_TYPES_ACTIVE = 'STORAGE_HELP_TASK_TYPES_ACTIVE';

export const STORAGE_SET_HELP_TASKS = 'STORAGE_SET_HELP_TASKS';
export const STORAGE_HELP_TASKS_ACTIVE = 'STORAGE_HELP_TASKS_ACTIVE';

export const STORAGE_SET_HELP_UNITS = 'STORAGE_SET_HELP_UNITS';
export const STORAGE_HELP_UNITS_ACTIVE = 'STORAGE_HELP_UNITS_ACTIVE';

export const STORAGE_SET_HELP_WORK_TYPES = 'STORAGE_SET_HELP_WORK_TYPES';
export const STORAGE_HELP_WORK_TYPES_ACTIVE = 'STORAGE_HELP_WORK_TYPES_ACTIVE';

export const STORAGE_SET_METADATA = 'STORAGE_SET_METADATA';
export const STORAGE_METADATA_ACTIVE = 'STORAGE_METADATA_ACTIVE';

export const STORAGE_USERS = 'STORAGE_SET_USERS';
export const STORAGE_USERS_ACTIVE = 'STORAGE_USERS_ACTIVE';

export const STORAGE_HELP_SUPPLIER_INVOICES = 'STORAGE_HELP_SUPPLIER_INVOICES';
export const STORAGE_HELP_SUPPLIER_INVOICES_ACTIVE = 'STORAGE_HELP_SUPPLIER_INVOICES_ACTIVE';

export const STORAGE_HELP_SUPPLIERS = 'STORAGE_HELP_SUPPLIERS';
export const STORAGE_HELP_SUPPLIERS_ACTIVE = 'STORAGE_HELP_SUPPLIERS_ACTIVE';
